# Site settings
title: bkero's Profile
email: bkero@bke.ro
description: > # this means to ignore newlines until "baseurl:"
  demo description
baseurl: "/project-gh-pages"
url: "http://bkero.github.io"
twitter_username: bkero
github_username:  bkero
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
